policies:
  - type: license
    spec:
      skipPaths:
        - .git/
        - target/
        - books/usage/book
        - books/commitments/book
      includeSuffixes:
        - .rs
      header: |
        /*
         * Copyright (2021) by Marcel Lambert.
         * This project is dual licensed under either MIT or Apache-2.0.
         */
  - type: commit
    spec:
      headerLength: 89
      dco: false
      gpg: false
      imperative: true
      maximumOfOneCommit: false
      requireCommitBody: false
      spellcheck:
        locale: UK
      conventional:
        types:
          - "build"
          - "ci"
          - "docs"
          - "feat"
          - "fix"
          - "perf"
          - "refactor"
          - "style"
          - "test"
        scopes:
          - "systems"
          - "generic"
          - "native"
          - "cocoa"
          - "mock"
          - "win"
          - "ios"
          - "android"
        descriptionLength: 72