unstable_features = true
wrap_comments = true
enum_discrim_align_threshold = 20
struct_field_align_threshold = 5
blank_lines_upper_bound = 5
format_code_in_doc_comments = true
format_strings = true
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
#license_template_path = "license_header_template.md"
match_block_trailing_comma = true
merge_derives = false
newline_style = "Unix"
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Always"
#report_todo = "Unnumbered"
use_field_init_shorthand = true