[hooks]
#pre-commit = [
#              "cargo fmt --all -- --check",              #run cargo format. don't automatically apply fixes
#              "cargo test --all --no-fail-fast --quiet", #run tests
#              "cargo clippy",                            #run cargo clippy
#              "cargo outdated --root-deps-only",         #we don't want outdated deps
#              "write-good */**/*.rs --parse",            #check if linguistic style is ok
#              "write-good *.md --parse",
#              "write-good *?/*.toml --parse",
#              "write-good ./commitmessage --parse",
#              "cargo lichking check"                    #check licenses
#             ]
pre-push = [
            "cargo test --all --no-fail-fast --quiet", #run tests
           ]
prepare-commit-msg = """set -e
                        if grep "^[^#;]" $1
                            then
                                echo "commit message provided, skipping default"
                            else
                                printf "$(cat commitmessage)\n$(cat $1)" > $1
                        fi"""

[logging]
verbose = true